version: '20.10.23'

services:
  scraper_container:
    build:
      context: .
      dockerfile: Dockerfile
    image: rt_scraper
    ports:
      - "5432:5432"
    volumes:
      - /Users/tom/Desktop/Data-Collection/Data-Collection/docker/raw_data:/app/raw_data
    tty: true
    stdin_open: true